#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 21 08:58:10 2025

@author: gokremtekir
"""
"""


1. Dosya Açma ve Kapatma

	•	Dosya Nedir?
	•	 Bir programda verileri saklamak veya geri almak için kullanılan bir kaynak.
	•	
        Dosya Açma (open):
	•	open() fonksiyonu, bir dosyayı açar veya yeni bir dosya oluşturur.
	•	
        Modlar:
	•      	"r": Okuma modu (varsayılan).
	•      	"w": Yazma modu (mevcut dosyayı sıfırlar).
	•      	"a": Ekleme modu (dosyanın sonuna yazar).
	•      	"x": Yeni bir dosya oluşturur, zaten mevcutsa hata verir.
	•
    	Dosya Kapatma (close):
	•	     Dosya ile işiniz bittiğinde kapatmak için kullanılır.
"""

# %% - Dosya açma ve yazma

# dosya = open("ornek.txt", "w")
# dosya.write("Merhaba Dünya")
# dosya.close()



# %% Dosya açma ve yazma

# with open("ornek.txt","w") as dosya:
#     dosya.write("Python ile dosya işlemleri yapıyorum")


# %% Dosyaya ifade ekleme

# with open("ornek.txt","a") as dosya:
#     dosya.write("\nOldukça eğlenceli")
    
    

# %% Dosya içeriğini okuma


# with open("ornek.txt","r") as dosya:
#     icerik = dosya.read()
#     print(icerik)

# %%



# with open("ornek.txt","r") as dosya:
#     satirlar = dosya.readlines()
#     for satir in satirlar:
#         print(satir.strip())
        
# print(satirlar[0])


# %%

# try:
#     with open("olmayandosya.txt", "r") as dosya:
#         print(dosya.read())
# except FileNotFoundError:
#     print("Dosya bulunamadı")

# %%

# try:
#     with open("ornek.txt", "x") as dosya:
#         dosya.write("Gökrem Tekir")
# except FileExistsError:
#     print("Bu dosya zaten var")



# %%

while True:
    print("\n1- Yeni Not Ekle")
    print("2- Tüm Notları Göster")
    print("3- Çıkış Yap")
    
    secim = input("Seçiminizi yapın: ")

    if secim == "1":
        not_ = input(" Notunuz nedir? ")
        with open("not_defteri.txt", "a") as dosya:
            dosya.write(not_ + "\n")
    elif secim == "2":
        with open("not_defteri.txt", "r") as dosya:
            print("\nTüm Notlar:")
            print(dosya.read())
    elif secim =="3":
        print("Çıkış yapılıyor")
        break
    else:
        print("Geçersiz Giriş")

