#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
1. Liste ile Ortalama Hesaplama
Görev:
    •   Kullanıcıdan bir öğrenci not listesi alarak listenin ortalamasını 
    hesaplayan bir program yazın.
    •   Kullanıcıdan sürekli olarak not girmesi istenecek ve kullanıcı -1 
    girdiğinde giriş işlemi sonlandırılacak.

Örnek Çıktı:
Notları girin (çıkmak için -1 yazın): 
85
90
78
-1
Ortalama: 84.33
"""

notlar = []

while True:
    not_girisi = input("Notları Girin (çıkış için -1):")
    
    if not_girisi == "-1":
        break
    
    try:
        not_degeri = float(not_girisi)
        notlar.append(not_degeri)
    except ValueError:
        print("Geçersiz veri girdiniz, lütfen sayı giriniz.")

if len(notlar) > 0:
    ortalama = sum(notlar) / len(notlar)
    print("Ortalama:", ortalama)
else:
    print("Hiç not girilmedi")
