#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 21 19:44:23 2025

@author: gokremtekir
"""

"""
Python: Modüller ve Paketler 

1. Hazır Modüllerin Kullanımı
    Modül Nedir?
	•	Python’da belirli işlevleri gerçekleştiren, 
    fonksiyonlar ve sınıflardan oluşan dosyalardır.
	•	Modülleri import anahtar kelimesiyle kullanabilirsiniz.

"""

# %%

# import math

# print(math.sqrt(16))
# print(math.factorial(5))
# print(math.pi)


# %%



# from datetime import datetime


# now=datetime.now()

# print("Şu anki zaman: ", now)

# print(f"Yıl: {now.year}, Ay: {now.month}, Gün: {now.day}")


# %%

# import os

# print(os.getcwd())

# os.mkdir("yeni_klasor")


# %%

# import random

# print(random.randint(1, 10))

# liste = ["elma", "armut", "çilek"]

# print(random.choice(liste))

# %%

# import sys

# sys.path.append("/Users/gokremtekir/spyder")

# import Geometrik_Alanlar



# %%


# import requests


# url = "https://raw.githubusercontent.com/gokremtekir/Python-Ornekleri/4e770d64c7d94d5839918c93008586899833ae4b/ATM%20Ekran%C4%B1"


# response = requests.get(url)

# exec(response.text)


# %%


# import requests

# url1 = "https://api.exchangerate-api.com/v4/latest/USD"
# url2 = "https://api.exchangerate-api.com/v4/latest/EUR"

# response1 = requests.get(url1)
# response2 = requests.get(url2)

# data1 = response1.json()
# data2 = response2.json()

# print("1 USD: ", data1["rates"]["TRY"], "TL")
# print("1 EUR: ", data2["rates"]["TRY"], "TL")


# %%


import time
import datetime
import requests


def update_exchange_rate():
    url1 = "https://api.exchangerate-api.com/v4/latest/USD"
    response1 = requests.get(url1)
    data1 = response1.json()
    print("1 USD: ", data1["rates"]["TRY"], "TL")
    


def wait_for_update():
    
    while True:
        now = datetime.datetime.now()
        
        if now.hour == 23 and now.minute == 23:
            update_exchange_rate()
            
            time.sleep(60)
            
        else:
            time.sleep(60)


if __name__ == "__main__":
    wait_for_update()
    
